### PR TITLE
Fix newer node

### PR DESCRIPTION
**Pull request by emirotin**
WIP: it's still failing, but I've solved couple of problems and will continue pushing to this branch.

### CODE REVIEW

**Comment by emirotin** [comment]
Sooooo... It works :)
I believe the changes I've made are fixing some real issues, both in code and the tests.
Note that I've dropped support for Node < 4 as I think it's impractical to have just to add support for now outdated 0.12

I've also manually tested with node7 on Windows and the tests have passed, but you may want to add AppVeyor CI to this module.

**Comment by wzrdtales** [comment]
> Note that I've dropped support for Node < 4 as I think it's impractical to have just to add support for now outdated 0.12

I'm fine with that, to make note of it we just push up to the next major version.

**Comment by emirotin** [comment]
Yes sure

**Comment by emirotin** [comment]
FYI I'm currently testing this in the real project and having some troubles - not sure why yet

**Comment by emirotin** [comment]
I've also manually tested it here https://github.com/resin-io/resin-cli/tree/proxy using Privoxy - seems to work fine

**Comment by emirotin** [comment]
Hey, I don't want to be pushy but any idea when this can be merged and published?
If for some reason you'd rather not do that we can go with our own fork, but I believe these changes to be beneficial to the community.

**Comment by wzrdtales** [comment]
@MiShibari Sry was travelling the last few days and therefor had no time to look in here.

Gonna merge it know, thanks again for your work on this!

**Comment by wzrdtales** [comment]
published as

+ global-tunnel-ng@2.0.0

**Comment by emirotin** [comment]
Nice, thank you!

**Pull request merged**
