### PR TITLE
Fix auth

### PR DESCRIPTION
**Pull request by emirotin**
Hey, me again :)

I've noticed I've improperly used the parsed basic auth, so this fixes it.
I've also exposed couple of useful things (proxy config and its stringified version) that I need in my app.

### CODE REVIEW

**Comment by wzrdtales** [comment]
Hey and thanks again :) Highly appreciate you effort!

**Comment by emirotin** [comment]
Thanks :)
Can you please publish it as 2.1.0 or 2.0.1 please?

**Comment by wzrdtales** [comment]
will do sry

**Comment by wzrdtales** [comment]
published as 
+ global-tunnel-ng@2.1.0

**Pull request merged**
