### PR TITLE
Changed engine configuration

### PR DESCRIPTION
**Pull request by MarcoScabbiolo**
Better engine configuration to allow it to run on all the versions of Node higher than the one previously configured.

### CODE REVIEW

**Comment by MarcoScabbiolo** [comment]
@wzrdtales Can you publish the package after merging this PR?

**Comment by MarcoScabbiolo** [comment]
@wzrdtales can you add me as a collaborator so I can help you mantaining this repo?

**Comment by wzrdtales** [comment]
Sry for the delay, and thanks for offering help! That is the open source spirit :tada: . WIll totally welcome it and will add you as a collaborator.

**Comment by wzrdtales** [comment]
Hit me up again the next days should I forget as always currently quite short on time.

**Comment by MarcoScabbiolo** [comment]
Great! Add me whenever you want, and to the npm repo as well if you don't mind. Thanks!

**Comment by MarcoScabbiolo** [comment]
Hello @wzrdtales are you still there?

**Comment by wzrdtales** [comment]
Yes sry :/ Will add you

**Comment by wzrdtales** [comment]
Need your npm name though.

**Comment by wzrdtales** [comment]
And sry, but I always say that, and I still am low on time, but things are changing so often and fast for me, no longer beautiful :/ But I hope to be able to integrate open source better again in my future company :)

**Comment by wzrdtales** [comment]
So not ment to ignore anyone.

**Comment by MarcoScabbiolo** [comment]
My NPM name is marcoscabbiolo . No worries, you're not alone and me and many others will gladly give a hand. Take care of what is most important for you, we'll still be here when you have some time to spare!

**Comment by wzrdtales** [comment]
I appreciate it, you're added, you just need to accept the github orga invitations and you're good to go :)

**Pull request merged**
